version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: django
      MYSQL_DATABASE: django
      MYSQL_USER: django
      MYSQL_PASSWORD: django
  web:
    depends_on:
      - db
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python src/manage.py runserver 0.0.0.0:8000
    entrypoint: /service/wait-for-it.sh db:3306 --
    ports:
      - "8000:8000"
    volumes:
      - ../src:/service/src